spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/rabbitmat_db
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
      dialect: PostgreSQLDialect
    show-sql: true
